### PR TITLE
Compatible with PostgreSQL 15

### PR DESCRIPTION
**Pull request by MGorkov**
Tested with PG15.2/Centos7

### CODE REVIEW

**Comment by proxy-m** [comment]
Nice, but... Do you want to break support of previous PostgreSQL versions? 

It is LTS.

**Comment by MGorkov** [comment]
Why do you think this will break support of previous versions?
I checked on versions starting from 9.6 and it works great

**Comment by rossnick** [comment]
Does anybody here have any experience in building this on Windows ? I've tried to do it with @MGorkov fork, I was able to get, not without pain, the dependencies built (wxwidget, libssh2), and I got to a point where I get linking errors when building pgadmin3.

**Comment by MGorkov** [comment]
I built it successfully for Windows using github workflow named MSBuild.
Download pgAdmin3 from the artefacts section of this workflow https://github.com/MGorkov/pgadmin3-lts/actions/runs/4355088750

**Comment by rossnick** [comment]
Wow, thanks ! @MGorkov

**Comment by proxy-m** [comment]
> Why do you think this will break support of previous versions? I checked on versions starting from 9.6 and it works great

How did you check it? Do you know all side effects?

1) You have changed PG_KEYWORD macros in [keywords.c](https://github.com/allentc/pgadmin3-lts/pull/22/commits/ef1f984864ffcf7b71da24238f0b4a2a39d61488#diff-f32f6dbc0dfc3bc2d062a617503d39abe1c9fe70088afeb80278e3566b7d669a) and [kwlist.h](https://github.com/allentc/pgadmin3-lts/pull/22/commits/ef1f984864ffcf7b71da24238f0b4a2a39d61488#diff-ad7c8038f5ee2b324dc558dc3410fe84f6c2ca3fdfaf5811917085387abf4a7f)

2) You have changed query (datname) from pg_database in [pgConn.cpp](https://github.com/allentc/pgadmin3-lts/pull/22/commits/ef1f984864ffcf7b71da24238f0b4a2a39d61488#diff-04517e1700512adfbd584e815d67ad86b48b173ca8b2ae1b257efa2639f9241b)

**Pull request merged**
