### PR TITLE
Small update for simple build with wxgtk3 and postgresql13 under Debian (Ubuntu)

### PR DESCRIPTION
**Pull request by proxy-m**

### CODE REVIEW

**Comment by allentc** [comment]
I have procrastinated merging this.  My apologies.

I drag my feet because I don't understand this.  kwlist.h is pulled in, yet there is no related code; one would expect to see some related logic that would utilize the lengthy list of keywords.  I'm sure this exists and I'm simply ignorant of how this works.  Can you shed some light?

Although the install instructions are greatly appreciated the 'If you are too lazy' language in README is a hang up.  The document is otherwise neutral in tone and should probably stay that way.

Thank you for the pull request.

**Comment by proxy-m** [comment]
How you build it under Debian/Ubuntu (linux) without kwlist.h ?

**Comment by SebDieBln** [comment]
> How you build it under Debian/Ubuntu (linux) without kwlist.h ?

Using the package [postgresql-server-dev-13](https://packages.ubuntu.com/impish/postgresql-server-dev-13)? This package contains a file with that name, but I haven't built on Linux, so it's just a guess. If that works the readme should probably mention that you do not need the server but only the server-dev package?

**Comment by proxy-m** [comment]
> kwlist.h is pulled in, yet there is no related code; one would expect to see some related logic that would utilize the lengthy list of keywords.

Search https://github.com/allentc/pgadmin3-lts/search?q=kwlist.h

shows that [`kwlist.h`](../blob/master/pgadmin/include/parser/kwlist.h) used on [pgadmin/db/keywords.c:33](../blob/master/pgadmin/db/keywords.c#L33) and then on [`ScanKeywordLookup(const char *text)`](../blob/master/pgadmin/db/keywords.c#L83).

Only `postgresql-server-dev-13`? Maybe, but programmer usually needs full server on localhost too.

**Comment by SebDieBln** [comment]
> Only `postgresql-server-dev-13`?

I did not check, but that package contains the mentioned file, so I guess you could build just with that package. Did you try it?

> ... programmer usually needs full server on localhost, too.

I agree that it is quite likely for a developer developing pgAdmin3 to have a server running on his local machine. But I argue that _quite likely_ is not enough to make it a requirement. However I do like to have that file in the source of pgAdmin3 because actually we want to only depend on [libpq-dev](https://packages.ubuntu.com/jammy/libpq-dev), not on the complete server. After all, we are developing a client, not a server.

**Comment by proxy-m** [comment]
I can not install `postgresql-server-dev-13`, because it may broke dependencies to clang and llvm on my build system, but I can temporary remove `postgresql-13` full server...

**Comment by proxy-m** [comment]
Hmm...
`configure: error: Could not find your PostgreSQL installation in /usr/lib/postgresql/13`

But maybe I can change configure options...

**Comment by proxy-m** [comment]
Yes, build success without postgresql-13. libpq-dev (and binary) is still used of course.  I'll change the README (comment optional dependencies).

$ dpkg -S /usr/bin/pg_config
libpq-dev: /usr/bin/pg_config

$ ls -lsahF ./pgadmin/pgadmin3 
13M -rwxrwxr-x 1 m m 13M Jan 16 02:51 ./pgadmin/pgadmin3*

**Pull request merged**
